name: Master
on:
  push
  schedule:
    - cron: '*/3 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Running
      run: |
        echo "Running!"